server:
  port: 8080
logging:
  config: logback.xml
#mybatis:
#  type-aliases-package: com.neo.model
spring:
  datasource:
    url: jdbc:mysql://192.168.0.5:3306/dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: elvis
    password: '!Q@W3e4r'
    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 2000
#      validationQuery: select 1
#      testOnBorrow: false
#      testOnReturn: false
#      testWhileIdle: true
#      filters: stat, wall
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: true
#        login-username: admin
#        login-password: 123

#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 20
#      idle-timeout: 500000
#      max-lifetime: 540000
#      connection-timeout: 60000
#      connection-test-query: SELECT 1
#      pool-name: elvis-pool

  redis:
    #Redis服务器IP地址
    host: 192.168.0.6
    #Redis服务器端口号
    port: 6379
    jedis:
      pool:
        #Redis服务器最大活跃数
        max-active: 20
        #Redis服务器最大空闲数
        max-idle: 8
        #Redis服务器最小空闲数
        min-idle: 0
        #Redis服务器链接最大超时20000
        max-wait: 20000