server:
  port: 8080
logging:
  config: logback.xml
#mybatis:
#  type-aliases-package: com.neo.model
spring:
  datasource:
    url: jdbc:mysql://192.168.0.5:3306/dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: elvis
    password: !Q@W3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver